---
# Areas
- name: area/docs
  color: "0e8a16"
- name: area/ansible
  color: "72ccf3"
- name: area/github
  color: "72ccf3"
- name: area/terraform
  color: "72ccf3"
- name: cluster/main
  color: "72ccf3"
# Renovate Types
- name: renovate/ansible
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/terraform
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "FFEC19"
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: enhancement
  color: "84b6eb"
- name: link-checker
  color: "7B55D7"
- name: question
  color: "cc317c"
