---
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: prettier
        name: Fix Prettier Formatting
        entry: prettier --write --config .github/linters/.prettierrc.yaml --ignore-path .github/linters/.prettierignore
        language: system
        types_or: [json, yaml, markdown, javascript, css, html]
        pass_filenames: true

      - id: terraform-fmt
        name: Fix Terraform Formatting
        entry: terraform fmt -recursive
        language: system
        files: \.tf$
        pass_filenames: false

      # - id: packer-fmt
      #   name: Fix Packer Formatting
      #   entry: packer fmt lab/provision/packer
      #   language: system
      #   files: \.pkr\.hcl$
      #   pass_filenames: false

      - id: shfmt
        name: Fix Shell Formatting
        entry: shfmt -w
        language: system
        types: [shell]
        pass_filenames: true

      - id: yamllint
        name: Check YAML Linting
        entry: yamllint -c .github/linters/.yamllint.yaml
        language: system
        types: [yaml]
        pass_filenames: true
        exclude: ^\.opencode/.*|^\.pre-commit-config\.yaml$

      - id: markdownlint
        name: Check Markdown Linting
        entry: markdownlint-cli2 --config .github/linters/.markdownlint-cli2.yaml
        language: system
        types: [markdown]
        pass_filenames: true

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
