---
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  ansible: .taskfiles/ansible
  lint: .taskfiles/lint
  opencode: .taskfiles/opencode
  packer: .taskfiles/packer
  pre-commit: .taskfiles/pre-commit
  terraform: .taskfiles/terraform

tasks:
  default:
    cmd: task --list
    silent: true
