---
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  ansible: .taskfiles/ansible
  packer: .taskfiles/packer
  pre-commit: .taskfiles/pre-commit
  sops: .taskfiles/sops
  terraform: .taskfiles/terraform

tasks:
  default:
    cmd: task --list
    silent: true
