---
version: "3"

vars:
  CLOUDFLARE_MODULE: "{{.ROOT_DIR}}/lab/provision/terraform/modules/cloudflare"

tasks:
  init:
    desc: "Initialize the Cloudflare module"
    dir: "{{.CLOUDFLARE_MODULE}}"
    cmds:
      - terraform init {{.CLI_ARGS}}
    preconditions:
      - sh: command -v terraform &>/dev/null
        msg: "terraform is required"

  plan:
    desc: "Plan Cloudflare module changes"
    dir: "{{.CLOUDFLARE_MODULE}}"
    cmds:
      - terraform plan {{.CLI_ARGS}}
    preconditions:
      - sh: command -v terraform &>/dev/null
        msg: "terraform is required"

  apply:
    desc: "Apply Cloudflare module changes"
    dir: "{{.CLOUDFLARE_MODULE}}"
    cmds:
      - terraform apply {{.CLI_ARGS}}
    preconditions:
      - sh: command -v terraform &>/dev/null
        msg: "terraform is required"
