domain: ENC[AES256_GCM,data:/2tIHs1oIzw=,iv:LCHCx19TYXnfCNRrP8UnsYFUuagsyydk6TmlLWKBs40=,tag:XiqA27bJkInH/LPvuqZ0dg==,type:str]
timezone: ENC[AES256_GCM,data:BMzbcl7zbF1apB8u+wFn,iv:+y+CxQR5ZJVErHThmRjfnowIwcEQFgxHmYOoL7mimx4=,tag:x6kNb8wKfyCu8QhBhD//UQ==,type:str]
github_repo: ENC[AES256_GCM,data:qfh3rnrYFmnnr4Z/rg==,iv:6oleSRBJTXLzRoHDY0DPBXFkmId0b7KC9kUSfG0IAPM=,tag:6s15lI2wH4oeaSZe2EBbzg==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:869935076354:key/4a38975b-065e-4cbc-b0d7-b6067418b38f
      aws_profile: ""
      created_at: "2026-09-25T17:15:37Z"
      enc: AQICAHh/rz75/nKbwI0RXq7iMBJYL7hlipIj6OLAOxfUHnkEVAEE3gVSP62rDORlHh4ufDobAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnM+iQYf5c6p3rnteAgEQgDuSwXt3k4ST+yTrZ50wOp67UTQ8Q++6ua1ItzNGs73YWAyCOGIg6Vz5oVTdd4E17FcXmkXvbprd0D+clw==
    - arn: arn:aws:kms:us-east-1:869935076354:key/6baaa7c8-967a-4fc5-9923-c0a938edfcf4
      aws_profile: ""
      created_at: "2026-09-25T17:15:37Z"
      enc: AQICAHiZo+cPAuO73jcHgXPcqIFyok2ddbznmCZaW01nCrJH5QElbifR5xyoSmtNee8rKBltAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0axnUMQ/xJLb1+MyAgEQgDuMWV7HY9eYP9Y84mGzZp/hwOhvE6t6xd8JZQdkRnVm0risO0/QQybrlObfEQNfWVnTbs15SVfWH9kCZA==
  lastmodified: "2026-09-25T17:15:37Z"
  mac: ENC[AES256_GCM,data:hyYLjddxWRZ5W5zm6ZEGkh20NQiCVw+0peqCcoYPuR3GbRnvWrAxYWrIWGXNTrywDpWxWuJnGdZD5x4gymToHVvkT9fxWSCE2aGEGjiRT1r8QuTo9vZnbj+YA0nS2FozKluVAqoiSPaHElw/KkeyQMxUYYDND6HEQ+zFycdpJ8Q=,iv:o5E5E39GtE/jb+atPvn5FCPijRrxFvMvDNT8HrtdlfA=,tag:KXDdwEaFUnXP3NS1A2pKcw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
